### ISSUE TITLE
negative values

### ISSUE THREAD

**Issue by nesergen** [JelteF/PyLaTeX#144]
How about support negative values in parameters?

It is my programm:
```
#! ./usr/bin/python2.7
# -*- coding: utf-8 -*-

from pylatex import Document,   Tabular,    MultiRow,  Package
from pylatex.utils import italic,  bold

import pylatex.base_classes.command as com

comm = com.Command('documentclass',options=com.Options('12pt', 'a4paper'), arguments='article')

doc = Document(fontenc='T1,T2C')

opt = com.Options(left='1cm',right='1cm',top='1cm',bottom='1cm',bindingoffset='0cm', headheight ='0mm',  hoffset = '2mm', voffset='-2mm')
doc.packages.append(Package('geometry', options=opt))
doc.packages.append(Package('extsizes', options=['14pt'] ))

table4 = Tabular('|l|c|l|')
table4.add_hline()
col1_cell = MultiRow(2, data=italic('span-2', escape=True))
col2_cell = MultiRow(2, data= bold('span-3'))
table4.add_row((col1_cell, bold(u'Кирилица, едрить её за ногу',escape=True), col2_cell ))
table4.add_hline(start=2,  end=2)
table4.add_row(('', u'Юникод, сапог ему врот', '' ))

table4.add_hline()
doc.append(table4)

doc.generate_pdf(u'/home/sergen/PythonExp/tex-exp/full' )
```

when I define a negative parameter in row  `opt = com.Options( ..parameters.. )`  like ` voffset='-2mm'`

then I get a line in the tex-file:
`\usepackage[voffset={-}2mm]{geometry}`

I think the minus sign should not be in brackets !

and An error occurs during the pdf-conversion:
```
>>> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./full.tex
LaTeX2e <2016/02/01>
Babel <3.9q> and hyphenation patterns for 10 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2cenc.def)
(/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2ccmr.fd))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/t2cenc.dfu)))
(/usr/share/texmf/tex/latex/lm/lmodern.sty)
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
! Missing number, treated as zero.
<to be read again> 
                   {
l.995 \Gm@process
                 
! Illegal unit of measure (pt inserted).
<to be read again> 
                   {
l.995 \Gm@process
                 

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.995 \Gm@process
                 
) (/usr/share/texlive/texmf-dist/tex/latex/extsizes/extsizes.sty

Package ExtSizes Warning: It is better to use one of the extsizes classes,
 if you can.

(/usr/share/texlive/texmf-dist/tex/latex/extsizes/size14.clo))
(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty) (./full.aux)

LaTeX Font Warning: Font shape `T2C/lmr/m/n' undefined
(Font)              using `T2C/cmr/m/n' instead on input line 10.

*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texmf/tex/latex/lm/ot1lmr.fd)
(/usr/share/texmf/tex/latex/lm/omllmm.fd)
(/usr/share/texmf/tex/latex/lm/omslmsy.fd)
(/usr/share/texmf/tex/latex/lm/omxlmex.fd)

LaTeX Font Warning: Font shape `T2C/lmr/m/it' undefined
(Font)              using `T2C/lmr/m/n' instead on input line 13.


LaTeX Font Warning: Font shape `T2C/lmr/bx/n' undefined
(Font)              using `T2C/lmr/m/n' instead on input line 13.

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./full.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 )
(see the transcript file for additional information) </home/sergen/.texmf-var/f
onts/pk/ljfour/lh/lh-t2c/lcrm1440.600pk> </home/sergen/.texmf-var/fonts/pk/ljfo
ur/lh/lh-t2c/lcrm1000.600pk>
Output written on full.pdf (1 page, 11950 bytes).
Transcript written on full.log.

Exception "unhandled CalledProcessError"
Command '['pdflatex', '--interaction=nonstopmode', 'full.tex']' returned non-zero exit status 1
File: /usr/local/lib/python2.7/dist-packages/pylatex/document.py, Line: 193
```

If a minus sign free of brackets, the conversion is successful.

**Comment by JelteF** [comment]
This problem should be fixed by wrapping the -2mm in NoEscape. I'm not sure
if special casing this is desirable.

**Comment by nesergen** [comment]
I wrote :
opt = com.Options( voffset=**NoEscape**(r'-2mm'))

Returned:
\usepackage[voffset=**{-}2mm**]{geometry}

Same problem...

**Comment by JelteF** [comment]
Hmm, that is a bug. Probably caused by the string join which adds all arguments together, not sure when I will have time to fix this. As a workaround you can use UnsafeCommand instead of Package.

**Comment by nesergen** [comment]
Some experimentssolved the bug. 
The packages argument 'options' can be 'str' , 'options' or 'list'  (https://jeltef.github.io/PyLaTeX/latest/pylatex/pylatex.package.html):
1) when I`ve tried "Options" It hasn`t helped
2) when I`ve tried "list" - the error has ocured:
```
File "/home/sergen/PythonExp/tex-exp/ltx.py", line 17
    doc.packages.append(Package('geometry', options=[voffset ='-2mm', left='1cm', right='1cm', top='1cm', bottom='1cm', bindingoffset='0cm',  headheight ='0mm',  hoffset = '2mm' ]))
                                                             ^
SyntaxError: invalid syntax
```
3) with ''str" argument all work well

partially SOLVED
